name: Update Dream RSS Feed

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 00:00 UTC에 실행
  workflow_dispatch:  # 수동 실행 가능

# 동시성 제어 - 같은 브랜치에 대해 한 번에 하나의 워크플로우만 실행
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false  # 진행 중인 작업 취소하지 않음

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug environment
        run: |
          pwd
          ls -la
          mkdir -p docs
          ls -la docs/
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub repository: ${{ github.repository }}"

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install openai feedgen

      - name: Generate RSS feed
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_rss.py

      - name: Check file changes
        run: |
          echo "파일 변경 확인 중..."
          git status
          ls -la docs/
          echo "RSS 파일 크기: $(stat -c%s docs/rss.xml 2>/dev/null || echo '파일 없음')"
          echo "used_keywords.json 내용:"
          cat used_keywords.json || echo "used_keywords.json 파일이 존재하지 않음"

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -f docs/rss.xml docs/index.html docs/last_update.txt used_keywords.json || true
          git status
          git commit -m "Update RSS feed for $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }} || git push origin HEAD:main

      # GitHub Pages 배포 상태 확인
      - name: Check GitHub Pages deployment
        run: |
          echo "GitHub Pages 배포 대기 중..."
          sleep 30
          echo "GitHub Pages 배포가 시작되었을 것입니다."
