name: Update Dream RSS Feed

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 00:00 UTC에 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug environment
        run: |
          pwd
          ls -la
          mkdir -p docs
          ls -la docs/

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install openai feedgen

      - name: Generate RSS feed
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_rss.py

      - name: Check file changes
        run: |
          echo "파일 변경 확인 중..."
          git status
          ls -la docs/
          cat used_keywords.json || echo "used_keywords.json 파일이 존재하지 않음"

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/rss.xml used_keywords.json || true
          git status
          git commit -m "Update RSS feed for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin HEAD:main || echo "Failed to push changes"
